force-app/main/default/objects/Anonymize_Configuration__mdt/Anonymize_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Anonymize Configuration</label>
    <pluralLabel>Anonymize Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Anonymize_Configuration__mdt/fields/Value_Type__c.field-meta.xml
<CustomField>
    <fullName>Value_Type__c</fullName>
    <label>Value Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CEL_AnonymizeUtil.cls
public with sharing class CEL_AnonymizeUtil {

     /**
     * anonymiser description
     * @param  {List<SObject>} accts
     * @param {List<Anonymize_Configuration__mdt> }fieldsValues
     * @return {Boolean}
     */
	public static Boolean anonymiser(List<SObject> accts,List<Anonymize_Configuration__mdt> fieldsValues) {
		for(SObject a : accts){
            for(Anonymize_Configuration__mdt f : fieldsValues){
                String fieldName = f.Field_Api_Name__c;
                String fieldValue = f.Value__c;

                if(fieldValue != null && fieldValue.contains('timestamp')){
                    DateTime dt = Datetime.now();
                    String formatedDt = dt.formatGMT('yyyyMMdd\'T\'HHmmss\'Z\'');
                    fieldValue =fieldValue.replace('timestamp', formatedDt);
                    
                }  if(f.Value_Type__c == 'Text' || f.Value_Type__c == 'Phone' ){
                    a.put(fieldName,  fieldValue);
                }
                else if(f.Value_Type__c == 'BOOLEAN'){
                    if(fieldValue == 'true' || fieldValue == 'True'){
                        a.put(fieldName,  true);
                    }
                    else{
                        a.put(fieldName,  false);
                    }
                }
                else if(f.Value_Type__c == 'Number' ){
                    a.put(fieldName, integer.valueof(fieldValue));
                }
                else if(f.Value_Type__c == 'DOUBLE'){
                    a.put(fieldName, double.valueof(fieldValue));
                }
                else if(f.Value_Type__c == 'NULL'){
                    a.put(fieldName,  null);
                }
                else if(f.Value_Type__c == 'DATE_NOW'){
                    a.put(fieldName,  Datetime.now());
                }
                else if(f.Value_Type__c == 'Date'){
                    a.put(fieldName,  Date.parse(fieldValue));
                }
                else{
                    a.put(fieldName,  null);
                }
            }
        }
        update accts;
        return true;
	}

    /**
     * anonymizeAccountAndRelation description
     * @param  {List<Account>} Account List to anonymize
     * @return {Boolean}
     */
    public static Boolean anonymizeAccountAndRelation(List<Account> accts) {
        Boolean anonymize = true;
        anonymize = anonymize && CEL_AccountMgr.anonymizeAccount(accts);
        anonymize = anonymize && CEL_CaseMgr.anonymizeCase(accts);
        CEL_IndividualMgr.updateIndividualAfterAnonymization(accts);
        return anonymize;
    }
    
}