force-app/main/default/objects/cel_transcodification__c/cel_transcodification__c.object-meta.xml
<CustomObject>
    <label>Transcodification</label>
    <nameField>
        <label>Transcodification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transcodifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cel_transcodification__c/fields/cel_transcodification_code__c.field-meta.xml
<CustomField>
    <fullName>cel_transcodification_code__c</fullName>
    <label>Transcodification Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_celinewearingstyle.recordType-meta.xml
<RecordType>
    <fullName>cel_celinewearingstyle</fullName>
    <active>true</active>
    <label>Celine Wearing Style</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_childrennumber.recordType-meta.xml
<RecordType>
    <fullName>cel_childrennumber</fullName>
    <active>true</active>
    <label>Children Number</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_colourtones.recordType-meta.xml
<RecordType>
    <fullName>cel_colourtones</fullName>
    <active>true</active>
    <label>Colour Tones</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_dressjacketcoatsize.recordType-meta.xml
<RecordType>
    <fullName>cel_dressjacketcoatsize</fullName>
    <active>true</active>
    <label>Dress Jacket Coat Size</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_familystatus.recordType-meta.xml
<RecordType>
    <fullName>cel_familystatus</fullName>
    <active>true</active>
    <label>Family Status</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_generalstyle.recordType-meta.xml
<RecordType>
    <fullName>cel_generalstyle</fullName>
    <active>true</active>
    <label>General Style</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_knitwearsize.recordType-meta.xml
<RecordType>
    <fullName>cel_knitwearsize</fullName>
    <active>true</active>
    <label>Knitwear Size</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_preferredappointmenttime.recordType-meta.xml
<RecordType>
    <fullName>cel_preferredappointmenttime</fullName>
    <active>true</active>
    <label>Preferred Appointment Time</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_preferredcontactmethod.recordType-meta.xml
<RecordType>
    <fullName>cel_preferredcontactmethod</fullName>
    <active>true</active>
    <label>Preferred Method Contact</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_shoessize.recordType-meta.xml
<RecordType>
    <fullName>cel_shoessize</fullName>
    <active>true</active>
    <label>Shoe size</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_spokenlanguage.recordType-meta.xml
<RecordType>
    <fullName>cel_spokenlanguage</fullName>
    <active>true</active>
    <label>Spoken Language</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_title.recordType-meta.xml
<RecordType>
    <fullName>cel_title</fullName>
    <active>true</active>
    <label>Title</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_topshirtsize.recordType-meta.xml
<RecordType>
    <fullName>cel_topshirtsize</fullName>
    <active>true</active>
    <label>Top shirt size</label>
</RecordType>

force-app/main/default/objects/cel_transcodification__c/recordTypes/cel_trousersskirtsize.recordType-meta.xml
<RecordType>
    <fullName>cel_trousersskirtsize</fullName>
    <active>true</active>
    <label>Troussers skirt size</label>
</RecordType>

force-app/main/default/classes/CEL_TranscodificationMgr.cls
public with sharing class CEL_TranscodificationMgr {  
    
    /**
     * getTitlesS: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getTitles() {
        return getTranscodifcationList('cel_title','','');
    }
    
    /**
     * getFamilyStatus: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getFamilyStatus() {
        return getTranscodifcationList('cel_familystatus','','');
    }
    
     /**
     * getChildrenNumber: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getChildrenNumber() {
        return getTranscodifcationList('cel_childrennumber','','');
    }
    
     /**
     * getCountries: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getCountries() {
        return getTranscodifcationList('Country','','');
    }
    
     /**
     * getPreferredContactMethod: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getPreferredContactMethod() {
        return getTranscodifcationList('cel_preferredcontactmethod','','');
    }
    
     /**
     * getSpokenLangage: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getSpokenLangage() {
        return getTranscodifcationList('cel_spokenlanguage','Name','ASC');
    }
    
    /**
     * getSpokenAppoitmentTime: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getPreferredAppointmentTime() {
        return getTranscodifcationList('cel_preferredappointmenttime','','');
    }
    
    /**
     * getTrousersSize: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getTrousersSize() {
        return getTranscodifcationList('cel_trousersskirtsize','','');
    }
    
    /**
     * getTop: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getTop() {
        return getTranscodifcationList('cel_topshirtsize','','');
    }
    
    /**
     * getDress: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getDress() {
        return getTranscodifcationList('cel_dressjacketcoatsize','','');
    }
    
    /**
     * getKnitwear: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getKnitwear() {
        return getTranscodifcationList('cel_knitwearsize','','');
    }
    
    /**
     * getShoes: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getShoes() {
        return getTranscodifcationList('cel_shoessize','','');
    }
    
    /**
     * getGeneralStyle: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getGeneralStyle() {
        return getTranscodifcationList('cel_generalstyle','','');
    }
    
    /**
     * getWearing: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getWearing() {
        return getTranscodifcationList('cel_celinewearingstyle','','');
    }
    
    /**
     * getColourTone: Return available lists for screen
     * @return {Map<String, List<Map<String, String>>>}
    */
    public static List<Map<String, String>> getColourTone() {
        return getTranscodifcationList('cel_colourtones','','');
    }

    /**
     * getTranscodifcationList: Return available lists for screen
     * @param recordTypeName
     * @return {Map<String, List<Map<String, String>>>}
    */
    private static List<Map<String, String>> getTranscodifcationList(String recordTypeName,String sortedField, String sortOrder) {
        String transcoRecordType = [SELECT Id FROM RecordType WHERE DeveloperName =: recordTypeName LIMIT 1].Id;
        String query = 'SELECT ID, Name from cel_transcodification__c where RecordtypeId = \'' + transcoRecordType+'\'';
        
        if(String.isNotBlank(sortedField)){
            query +=' ORDER BY '+sortedField;
            if(String.isNotBlank(sortOrder)){
                query +=' '+sortOrder;
            }
        }
        
        List<cel_transcodification__c> transcodification  = Database.query(query);
        
        List<Map<String, String>> res = new List<Map<String, String>>();
        res.add(new Map<String, String>{
                'value' => '',
                'label' => ''
            });
        for(cel_transcodification__c t : transcodification)
        {
            res.add(new Map<String, String>{
                'value' => t.Id,
                'label' => t.Name
            });
        }
        
        return res;
    }
    
    /**
    * getTranscodificationBySetId : return the list transcodifications object By set d'Ids
    * @param {Set<Id>} transcoIds
    * @return {List<cel_transcodification__c>}
    */
    public static List<cel_transcodification__c> getTranscodificationBySetId(Set<Id> transcoIds){
        List<cel_transcodification__c> transcodifications = new List<cel_transcodification__c>();
        
        transcodifications = [SELECT Id, Name, cel_transcodification_code__c 
                              FROM cel_transcodification__c 
                              WHERE Id IN :transcoIds ORDER BY Name];
        
        return transcodifications;
    }
    
    /**
    * getTranscodificationByCodes : return the list transcodifications object By list of codes
    * @param {List<String>} transcoIds
    * @return {List<cel_transcodification__c>}
    */
    public static List<cel_transcodification__c> getTranscodificationByCodes(List<String> transcoCodes){
        List<cel_transcodification__c> transcodifications = new List<cel_transcodification__c>();
        
        transcodifications = [SELECT Id, Name, cel_transcodification_code__c 
                               FROM cel_transcodification__c 
                               WHERE cel_transcodification_code__c IN :transcoCodes
                               ORDER BY Name];
        
        return transcodifications;
    }
}