force-app/main/default/objects/CEL_Configurations__c/CEL_Configurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>CEL_Configurations</label>
</CustomObject>

force-app/main/default/objects/CEL_Configurations__c/fields/cel_gdpr_report_campaign__c.field-meta.xml
<CustomField>
    <fullName>cel_gdpr_report_campaign__c</fullName>
    <label>GDPR Report Campaign</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEL_Configurations__c/fields/cel_gdpr_report_case__c.field-meta.xml
<CustomField>
    <fullName>cel_gdpr_report_case__c</fullName>
    <label>GDPR Report Case</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEL_Configurations__c/fields/cel_gdpr_report_transactions__c.field-meta.xml
<CustomField>
    <fullName>cel_gdpr_report_transactions__c</fullName>
    <label>GDPR Report Transactions</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEL_Configurations__c/fields/cel_gpdr_report_customer_card__c.field-meta.xml
<CustomField>
    <fullName>cel_gpdr_report_customer_card__c</fullName>
    <label>GDPR Report Customer Card</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEL_Configurations__c/fields/cel_interface_user_id__c.field-meta.xml
<CustomField>
    <fullName>cel_interface_user_id__c</fullName>
    <label>Interface User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEL_Configurations__c/fields/cel_report_campaign_action__c.field-meta.xml
<CustomField>
    <fullName>cel_report_campaign_action__c</fullName>
    <label>Report Campaign Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEL_Configurations__c/fields/cel_report_campaign_lines__c.field-meta.xml
<CustomField>
    <fullName>cel_report_campaign_lines__c</fullName>
    <label>Report Campaign Lines</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEL_Configurations__c/fields/cel_report_campaign_members__c.field-meta.xml
<CustomField>
    <fullName>cel_report_campaign_members__c</fullName>
    <label>Report Campaign Members</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEL_Configurations__c/fields/cel_report_campaign_transactions__c.field-meta.xml
<CustomField>
    <fullName>cel_report_campaign_transactions__c</fullName>
    <label>Report Campaign Transactions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CEL_Configurations__c/fields/cel_task_open_status__c.field-meta.xml
<CustomField>
    <fullName>cel_task_open_status__c</fullName>
    <label>Task open status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CEL_CustomSettingsMgr.cls
public with sharing class CEL_CustomSettingsMgr {
    /**
     * The SINGLETON handle to the instance
     */
    private static CEL_CustomSettingsMgr self;


    /**
     * Initialize the SINGLETON instance or return it if already exists
     *
     * @returns {SSCSiteCustomSettingHelper}
     */
    public static CEL_CustomSettingsMgr self() {
        if (self != null) {
            return self;
        }

        // To create org wide defaults in new org automatically. This will prevent NPE's in future.
        if (CEL_Configurations__c.getInstance() == null) {
            upsert new CEL_Configurations__c(SetupOwnerId = Userinfo.getOrganizationId());
        }

        self = new CEL_CustomSettingsMgr();
        return self;
    }

    /**
    * CEL_CustomSettingsMgr: private constructor of singleton 
    * to disable class standard instantiation
    */
    private CEL_CustomSettingsMgr() {}

    /**
    * getInterfaceUserId: return interface user Id
    * @return {String}
    */
    public String getInterfaceUserId() {
        return CEL_Configurations__c.getInstance().cel_interface_user_id__c;
    }

    /**
    * getGdprReportCustomerCard: return GDPR Customer Card Report Id
    * @return {String}
    */
    public String getGdprReportCustomerCard() {
        return CEL_Configurations__c.getInstance().cel_gpdr_report_customer_card__c;
    }

    /**
    * getGdprReportTransaction: return GDPR Transaction Report Id
    * @return {String}
    */
    public String getGdprReportTransaction() {
        return CEL_Configurations__c.getInstance().cel_gdpr_report_transactions__c;
    }

    /**
    * getGdprReportCampaign: return GDPR Campaign Report Id
    * @return {String}
    */
    public String getGdprReportCampaign() {
        return CEL_Configurations__c.getInstance().cel_gdpr_report_campaign__c;
    }

    /**
    * getGdprReportCase: return GDPR Case Report Id
    * @return {String}
    */
    public String getGdprReportCase() {
        return CEL_Configurations__c.getInstance().cel_gdpr_report_case__c;
    }

    /**
    * getReportCampaignIdAction: return campaign action Report Id
    * @return {String}
    */
    public String getReportCampaignIdAction() {
        return CEL_Configurations__c.getInstance().cel_report_campaign_action__c;
    }
    
    /**
    * getReportCampaignIdMembers: return campaign members Report Id
    * @return {String}
    */
    public String getReportCampaignIdMembers() {
        return CEL_Configurations__c.getInstance().cel_report_campaign_members__c;
    }
    
    /**
    * getReportCampaignIdTransactions: return campaign transactoins Report Id
    * @return {String}
    */
    public String getReportCampaignIdTransactions() {
        return CEL_Configurations__c.getInstance().cel_report_campaign_transactions__c;
    }
    
    /**
    * getReportCampaignIdLines: return campaign Lines Report Id
    * @return {String}
    */
    public String getReportCampaignIdLines() {
        return CEL_Configurations__c.getInstance().cel_report_campaign_lines__c;
    }
    
    /**
    * getTaskOpenStatuses: return the open statuses of Task
    * @return {Set<String>}
    */
    public Set<String> getTaskOpenStatuses() {
        String openStatusesAsString = CEL_Configurations__c.getInstance().cel_task_open_status__c;
        List<String> listOfOpenStatuses = String.isNotBlank(openStatusesAsString) ? openStatusesAsString.split(',') : null;
        
        Set<String> setOfOpenStatuses = listOfOpenStatuses != null ? new Set<String>(listOfOpenStatuses) : new Set<String>();
        return setOfOpenStatuses;
    }
}