force-app/main/default/objects/cel_email_task__mdt/cel_email_task__mdt.object-meta.xml
<CustomObject>
    <label>Email Task</label>
    <pluralLabel>Email Tasks</pluralLabel>
</CustomObject>

force-app/main/default/objects/cel_email_task__mdt/fields/cel_end_date__c.field-meta.xml
<CustomField>
    <fullName>cel_end_date__c</fullName>
    <label>End Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/cel_email_task__mdt/fields/cel_marked_on_entry__c.field-meta.xml
<CustomField>
    <fullName>cel_marked_on_entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marked On Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cel_email_task__mdt/fields/cel_priority__c.field-meta.xml
<CustomField>
    <fullName>cel_priority__c</fullName>
    <label>Priority</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cel_email_task__mdt/fields/cel_start_date__c.field-meta.xml
<CustomField>
    <fullName>cel_start_date__c</fullName>
    <label>Start Date</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/cel_email_task__mdt/fields/cel_task__c.field-meta.xml
<CustomField>
    <fullName>cel_task__c</fullName>
    <label>Task</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cel_email_task__mdt/fields/cel_template__c.field-meta.xml
<CustomField>
    <fullName>cel_template__c</fullName>
    <label>Template</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/cel_email_task__mdt/fields/cel_type__c.field-meta.xml
<CustomField>
    <fullName>cel_type__c</fullName>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cel_metadata_segment_map__mdt/cel_metadata_segment_map__mdt.object-meta.xml
<CustomObject>
    <label>Metadata Segment Map</label>
    <pluralLabel>Metadata Segment Maps</pluralLabel>
</CustomObject>

force-app/main/default/objects/cel_metadata_segment_map__mdt/fields/cel_Email_Task__c.field-meta.xml
<CustomField>
    <fullName>cel_Email_Task__c</fullName>
    <label>Email Task</label>
    <referenceTo>cel_email_task__mdt</referenceTo>
    <relationshipLabel>Metadata Segment Maps</relationshipLabel>
    <relationshipName>Metadata_Segment_Maps</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/cel_metadata_segment_map__mdt/fields/cel_related_segment__c.field-meta.xml
<CustomField>
    <fullName>cel_related_segment__c</fullName>
    <label>Segment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CEL_CustomMetadataMgr.cls
public class CEL_CustomMetadataMgr {
    
    /**
    * getRelatedTaskCustomMetadata: get the related custom metadata of the task
    * @param  {String}  api name of the custom metadata
    * @return cel_email_task__mdt
    */
    public static cel_email_task__mdt getRelatedTaskCustomMetadata(String apiName) {
        cel_email_task__mdt taskCustomMetadata = new cel_email_task__mdt();
        taskCustomMetadata =[Select Id, DeveloperName, cel_end_date__c,cel_marked_on_entry__c,
                             cel_priority__c,cel_start_date__c,cel_task__c,cel_template__c,cel_type__c
                             From cel_email_task__mdt
                             Where DeveloperName = :apiName];
        
        return taskCustomMetadata;
    }
    
    /**
    * getConcernedSegmentSet: get the related segments set tp the tasl
    * @param  {Id}  id of the custom metadata email task
    * @return Set<String>
    */
    public static Set<String> getConcernedSegmentSet(Id metadataId) {
        Set<String> concernedSegmentList = new Set<String>();
        
        List<cel_metadata_segment_map__mdt> listOfMapRelatedToMetadata = new List<cel_metadata_segment_map__mdt>();

        listOfMapRelatedToMetadata = [Select Id, DeveloperName, cel_related_segment__c, cel_Email_Task__c
                                      From cel_metadata_segment_map__mdt
                                      Where cel_Email_Task__c = :metadataId];
        
        if(listOfMapRelatedToMetadata != null && !listOfMapRelatedToMetadata.isEmpty()){
            for(cel_metadata_segment_map__mdt metadataSegmentMap : listOfMapRelatedToMetadata){
               concernedSegmentList.add(metadataSegmentMap.cel_related_segment__c); 
            } 
            
        }
        
        return concernedSegmentList;
    }

}