force-app/main/default/objects/cel_Campaign_Member_Status__c/cel_Campaign_Member_Status__c.object-meta.xml
<CustomObject>
    <label>Campaign Member Status</label>
    <nameField>
        <displayFormat>CMS-{000000}</displayFormat>
        <label>Campaign Member Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Campaign__c.field-meta.xml
<CustomField>
    <fullName>cel_Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Member Statuses</relationshipLabel>
    <relationshipName>Campaign_Member_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Purchasing__c.field-meta.xml
<CustomField>
    <fullName>cel_Purchasing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Purchasing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CEL_CampaignMemberStatusTriHdler_TEST.cls
@istest
public class CEL_CampaignMemberStatusTriHdler_TEST {

    @isTest
    static void theTest()
    {
        List<Recordtype> listRec = [select id, name from recordtype where 
                                    developerName = 'ParentAction' or developerName = 'ChildAction'
                                    order by developerName ];
        Campaign c = new Campaign(
                                    recordtypeid=listRec.get(0).id,
            						name='TEst',
            						cel_Category__c = 'Collection',
                                    cel_SubCatergory__c = 'Collectionlaunch',
            						startDate = System.Today(),
            						enddate = System.Today() + 15
                                 );
        insert c;
        
        cel_Campaign_Member_Status__c cms = new cel_Campaign_Member_Status__c( cel_Campaign__c = c.id,
                                                                              CurrencyIsoCode='USD');
        insert cms;
        string theName = cms.name;
        Test.startTest();
        
        c.cel_Category__c = 'CARESReward';
        c.cel_SubCatergory__c = 'Runway';
        update c;
        
        cms.cel_Purchasing__c = TRUE;
        update cms;
        
        //The delete test
        delete cms;
        
        
      
        Test.stopTest();
    }
    
    
     @isTest
    static void theTest2()
    {
        List<Recordtype> listRec = [select id, name from recordtype where 
                                    developerName = 'ParentAction' or developerName = 'ChildAction'
                                    order by developerName ];
        Campaign c = new Campaign(
                                    recordtypeid=listRec.get(0).id,
            						name='TEst',
            						cel_Category__c = 'Collection',
                                    cel_SubCatergory__c = 'Collectionlaunch',
            						startDate = System.Today(),
            						enddate = System.Today() + 15
                                 );
        insert c;
        
        cel_Campaign_Member_Status__c cms = new cel_Campaign_Member_Status__c( cel_Campaign__c = c.id,
                                                                              CurrencyIsoCode='USD');
        insert cms;
        string theName = cms.name;
        Test.startTest();
        
      
        delete cms;
        
        
        //undelete records
        cel_Campaign_Member_Status__c[] savedcmss = [SELECT Id, Name FROM cel_Campaign_Member_Status__c WHERE Name = :theName ALL ROWS];
       try 
       {
            undelete savedcmss;
        } catch (DmlException e) {
            // Process exception here
        }
        
         //The delete test
      
        Test.stopTest();
    }
    
}