force-app/main/default/objects/cel_Campaign_Member_Status__c/cel_Campaign_Member_Status__c.object-meta.xml
<CustomObject>
    <label>Campaign Member Status</label>
    <nameField>
        <displayFormat>CMS-{000000}</displayFormat>
        <label>Campaign Member Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Campaign__c.field-meta.xml
<CustomField>
    <fullName>cel_Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Member Statuses</relationshipLabel>
    <relationshipName>Campaign_Member_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Contact__c.field-meta.xml
<CustomField>
    <fullName>cel_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Clienteling Action History (Contact)</relationshipLabel>
    <relationshipName>Campaign_Member_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_ext_account_id__c.field-meta.xml
<CustomField>
    <fullName>cel_ext_account_id__c</fullName>
    <description>Customer Code Céline</description>
    <externalId>true</externalId>
    <label>cel_ext_account_id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cel_Transaction__c/cel_Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cel_Transaction__c/fields/cel_AccountId__c.field-meta.xml
<CustomField>
    <fullName>cel_AccountId__c</fullName>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master, Slave</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions (Customer)</relationshipLabel>
    <relationshipName>Transactions1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cel_Transaction__c/fields/cel_sale_date__c.field-meta.xml
<CustomField>
    <fullName>cel_sale_date__c</fullName>
    <label>Sale date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cel_Transaction__c/fields/cel_store__c.field-meta.xml
<CustomField>
    <fullName>cel_store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Store</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions (Store Code)</relationshipLabel>
    <relationshipName>Transactions2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cel_Transaction_Line__c/cel_Transaction_Line__c.object-meta.xml
<CustomObject>
    <label>Transaction Line</label>
    <nameField>
        <label>Transaction Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cel_Transaction_Line__c/fields/cel_net_value_local_tax_inc_eur__c.field-meta.xml
<CustomField>
    <fullName>cel_net_value_local_tax_inc_eur__c</fullName>
    <label>Net Value Local Tax Inc Eur</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/cel_Transaction_Line__c/fields/cel_Product2Id__c.field-meta.xml
<CustomField>
    <fullName>cel_Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Transactions Line</relationshipLabel>
    <relationshipName>Transactions_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cel_Transaction_Line__c/fields/cel_transaction__c.field-meta.xml
<CustomField>
    <fullName>cel_transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>cel_Transaction__c</referenceTo>
    <relationshipLabel>Transactions Line</relationshipLabel>
    <relationshipName>Transactions_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cel_transcodification__c/cel_transcodification__c.object-meta.xml
<CustomObject>
    <label>Transcodification</label>
    <nameField>
        <label>Transcodification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transcodifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cel_transcodification__c/fields/cel_transcodification_code__c.field-meta.xml
<CustomField>
    <fullName>cel_transcodification_code__c</fullName>
    <label>Transcodification Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CEL_CampaignController_TEST.cls
@isTest
public class CEL_CampaignController_TEST {
    
    @isTest
    static void testCampaignController() {
        // Create Transco
        ID countryRtID =  CEL_Constants.transcoCountryRtID;
        ID regionRtID =  CEL_Constants.transcoRegionRtID;
        cel_transcodification__c transco03 = new cel_transcodification__c();
        transco03.Name = 'EMEA';
        transco03.RecordTypeID = regionRtID;
        transco03.cel_transcodification_code__c = 'EMEA';
        insert transco03;
        
        system.assertNotEquals(null, transco03);
        
        // Create stores
        ID storeRtID =  CEL_Constants.storeRecordType;
        String storeStatusOpen = CEL_Constants.storeStatus.get('Open');
        Account store01 = new Account(Name='Store 01', RecordTypeID =  storeRtID);
        Account store02 = new Account(Name='Store 02', RecordTypeID =  storeRtID);
        
        store01.cel_addr_1_country__c = 'FRA';
        store01.cel_store_status__c = storeStatusOpen;
        store01.cel_store_area__c = String.valueOf(transco03.Id);
        store02.cel_addr_1_country__c = 'GBR';
        store02.cel_store_status__c = storeStatusOpen;
        store02.cel_store_area__c = String.valueOf(transco03.Id);
        
        insert store01;
        insert store02;
        
        Campaign c0 = new Campaign();
        c0.RecordTypeId = CEL_Constants.campaignParentRecordType;
        c0.Name = 'TEST';
        c0.startDate = Date.Today().addDays(-10);
        c0.endDate = Date.Today().addDays(+10);
        c0.cel_level__c = '1';
        insert c0;
        update c0;
        
        Campaign c1 = new Campaign();
        c1.RecordTypeId = CEL_Constants.campaignParentRecordType;
        c1.ParentId = c0.id;
        c1.Name = 'TEST';
        c1.startDate = Date.Today().addDays(-10);
        c1.endDate = Date.Today().addDays(+10);
        c1.cel_level__c = '1';
        insert c1;
        update c1;
        
        Campaign c = CEL_CampaignController.getCampaignDetails(c1.Id);
        system.assertNotEquals(null, c);
        
        Map<String,Map<String, String>> results = new Map<String,Map<String, String>>();
        results = CEL_CampaignController.initPicklistClienteling(String.valueOf(c1.Id), false);
        system.assertNotEquals(0, results.size());
        
        results = new Map<String,Map<String, String>>();
        results = CEL_CampaignController.initPicklistClienteling(String.valueOf(c1.Id), true);
        system.assertNotEquals(0, results.size());
        
        Map<String, String> results2 = new Map<String, String>();
        results2 = CEL_CampaignController.getCountriesListByRegion(String.valueOf(transco03.Id));
        system.assertNotEquals(0, results2.size()); 
        
        results2 = new Map<String, String>();
        results2 = CEL_CampaignController.getStoresListByCountry('FRA');
        system.assertNotEquals(0, results2.size());
        
        results2 = new Map<String, String>();
        results2 = CEL_CampaignController.getStoresListByCountry('GBR');
        system.assertNotEquals(0, results2.size());
        
        String storeRecordType = CEL_Constants.storeRecordType;
        List<Account> allStores = [SELECT Id,
                                           cel_long_name__c,
                                           cel_store_area__c,
                                           cel_addr_1_country__c
                                           FROM Account 
                                           WHERE RecordTypeId =: storeRecordType
                                           ORDER BY cel_long_name__c];
        
        Boolean isSave = CEL_CampaignController.savePicklistClienteling(String.valueOf(c1.Id), String.valueOf(allStores.get(0).Id));
        system.assertNotEquals(false, isSave);
        
        Map<String, List<String>> result = CEL_CampaignController.getRegionCountryStoresByCampaignId(c1.Id);
        system.assertNotEquals(0, result.size());
    }
    
    @isTest
    static void testGetDetailAndMakeCalcul() {
        Account s = new Account();
        s.Name = 'Paris';
        s.recordTypeId = CEL_Constants.storeRecordType;
        insert s;
        
        Campaign c1 = new Campaign();
        c1.RecordTypeId = CEL_Constants.campaignParentRecordType;
        c1.Name = 'TEST';
        c1.startDate = Date.Today().addDays(-10);
        c1.endDate = Date.Today().addDays(+10);
        c1.cel_level__c = '1';
        c1.IsActive = true;
        insert c1;
        update c1;
        
        Campaign c2 = new Campaign();
        c2.RecordTypeId = CEL_Constants.campaignParentRecordType;
        c2.ParentId = c1.Id;
        c2.Name = 'TEST';
        c2.startDate = Date.Today().addDays(-10);
        c2.endDate = Date.Today().addDays(+10);
        c2.cel_level__c = '2';
        c2.IsActive = true;
        insert c2;
        update c2;
        
        Campaign c3 = new Campaign();
        c3.RecordTypeId = CEL_Constants.campaignEnfantRecordType;
        c3.ParentId = c2.Id;
        c3.Name = 'TEST';
        c3.startDate = Date.Today().addDays(-10);
        c3.endDate = Date.Today().addDays(+10);
        c3.cel_level__c = '3';
        c3.IsActive = true;
        insert c3;
        update c3;
        
        Campaign c4 = new Campaign();
        c4.RecordTypeId = CEL_Constants.campaignEnfantRecordType;
        c4.ParentId = c3.Id;
        c4.Name = 'TEST';
        c4.startDate = Date.Today().addDays(-10);
        c4.endDate = Date.Today().addDays(+10);
        c4.cel_level__c = '4';
        c4.IsActive = true;
        insert c4;
        update c4;
        
        List<Campaign> allC = New List<Campaign>();
        allC.add(c4);
        allC.add(c3);
        allC.add(c2);
        allC.add(c1);
        
        Account a = new Account();
        a.LastName = 'Test';
        a.cel_ext_account_id__c = 'b';
        a.recordTypeId = CEL_Constants.peronAccountRtID;
        insert a;
        update a;
        
        Contact ctt = [SELECT Id, LastName, AccountId FROM Contact WHERE AccountId =: a.id ];
        
        cel_Campaign_Member_Status__c cms = new cel_Campaign_Member_Status__c();
        cms.cel_Campaign__c = c4.Id;
        cms.cel_Contact__c = ctt.Id;
        insert cms;
        
        CampaignMember cm = new CampaignMember();
        cm.CampaignId = c4.Id;
        cm.ContactId = ctt.Id;
        insert cm;
        
        cel_Transaction__c transactions = new cel_Transaction__c();
        transactions.cel_AccountId__c = a.Id;
        transactions.cel_sale_date__c = Date.today();
        transactions.cel_store__c = s.id;
        insert transactions;
        
        Product2 p1 = new Product2();
        p1.Name = 'Product 01';
        p1.cel_product_category__c = 'BAGS';
        insert p1;
        
        Product2 p2 = new Product2();
        p2.Name = 'Product 02';
        p2.cel_product_category__c = 'SHOES';
        insert p2;
        
        
        cel_Transaction_Line__c line01 = new cel_Transaction_Line__c();
        line01.cel_transaction__c = transactions.Id;
        line01.cel_Product2Id__c = p1.Id;
        line01.cel_net_value_local_tax_inc_eur__c = 100;
        insert line01;
        
        cel_Transaction_Line__c line02 = new cel_Transaction_Line__c();
        line02.cel_transaction__c = transactions.Id;
        line02.cel_Product2Id__c = P2.Id;
        line01.cel_net_value_local_tax_inc_eur__c = 10;
        insert line02;
        
        CEL_CampaignController.getDetailAndMakeCalcul(String.valueOf(c4.Id));
        CEL_CampaignController.getDetailAndMakeCalcul(String.valueOf(c3.Id));
        CEL_CampaignController.getDetailAndMakeCalcul(String.valueOf(c2.Id));
        CEL_CampaignController.getDetailAndMakeCalcul(String.valueOf(c1.Id));
    }
}