force-app/main/default/objects/cel_Campaign_Member_Status__c/cel_Campaign_Member_Status__c.object-meta.xml
<CustomObject>
    <label>Campaign Member Status</label>
    <nameField>
        <displayFormat>CMS-{000000}</displayFormat>
        <label>Campaign Member Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Campaign__c.field-meta.xml
<CustomField>
    <fullName>cel_Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Member Statuses</relationshipLabel>
    <relationshipName>Campaign_Member_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Contact__c.field-meta.xml
<CustomField>
    <fullName>cel_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Clienteling Action History (Contact)</relationshipLabel>
    <relationshipName>Campaign_Member_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_ext_account_id__c.field-meta.xml
<CustomField>
    <fullName>cel_ext_account_id__c</fullName>
    <description>Customer Code Céline</description>
    <externalId>true</externalId>
    <label>cel_ext_account_id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cel_Transaction__c/cel_Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cel_Transaction__c/fields/cel_AccountId__c.field-meta.xml
<CustomField>
    <fullName>cel_AccountId__c</fullName>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Master, Slave</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Transactions (Customer)</relationshipLabel>
    <relationshipName>Transactions1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cel_Transaction__c/fields/cel_sale_date__c.field-meta.xml
<CustomField>
    <fullName>cel_sale_date__c</fullName>
    <label>Sale date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/cel_Transaction_Line__c/cel_Transaction_Line__c.object-meta.xml
<CustomObject>
    <label>Transaction Line</label>
    <nameField>
        <label>Transaction Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cel_Transaction_Line__c/fields/cel_net_value_local_tax_inc_eur__c.field-meta.xml
<CustomField>
    <fullName>cel_net_value_local_tax_inc_eur__c</fullName>
    <label>Net Value Local Tax Inc Eur</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/cel_Transaction_Line__c/fields/cel_Product2Id__c.field-meta.xml
<CustomField>
    <fullName>cel_Product2Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Transactions Line</relationshipLabel>
    <relationshipName>Transactions_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cel_Transaction_Line__c/fields/cel_transaction__c.field-meta.xml
<CustomField>
    <fullName>cel_transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>cel_Transaction__c</referenceTo>
    <relationshipLabel>Transactions Line</relationshipLabel>
    <relationshipName>Transactions_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CEL_KpiCrossSellingBatch_TEST.cls
@isTest
public class CEL_KpiCrossSellingBatch_TEST {
    
    @isTest
    static void testCEL_KpiCrossSellingBatch() {
        Test.startTest();
        
        Campaign c1 = new Campaign();
        c1.RecordTypeId = CEL_Constants.campaignParentRecordType;
        c1.Name = 'TEST';
        c1.startDate = Date.Today().addDays(-10);
        c1.endDate = Date.Today().addDays(+10);
        c1.cel_level__c = '1';
        insert c1;
        update c1;
        
        Campaign c2 = new Campaign();
        c2.RecordTypeId = CEL_Constants.campaignParentRecordType;
        c2.ParentId = c1.Id;
        c2.Name = 'TEST';
        c2.startDate = Date.Today().addDays(-10);
        c2.endDate = Date.Today().addDays(+10);
        c2.cel_level__c = '2';
        insert c2;
        update c2;
        
        Campaign c3 = new Campaign();
        c3.RecordTypeId = CEL_Constants.campaignEnfantRecordType;
        c3.ParentId = c2.Id;
        c3.Name = 'TEST';
        c3.startDate = Date.Today().addDays(-10);
        c3.endDate = Date.Today().addDays(+10);
        c3.cel_level__c = '3';
        insert c3;
        update c3;
        
        Campaign c4 = new Campaign();
        c4.RecordTypeId = CEL_Constants.campaignEnfantRecordType;
        c4.ParentId = c3.Id;
        c4.Name = 'TEST';
        c4.startDate = Date.Today().addDays(-10);
        c4.endDate = Date.Today().addDays(+10);
        c4.cel_level__c = '4';
        insert c4;
        update c4;
        
        List<Campaign> allC = New List<Campaign>();
        allC.add(c4);
        allC.add(c3);
        allC.add(c2);
        allC.add(c1);
        
        Account a = new Account();
        a.LastName = 'Test';
        a.cel_ext_account_id__c = 'b';
        a.recordTypeId = CEL_Constants.peronAccountRtID;
        insert a;
        update a;
        
        Contact ctt = [SELECT Id, LastName, AccountId FROM Contact WHERE AccountId =: a.id ];
        
        cel_Campaign_Member_Status__c cms = new cel_Campaign_Member_Status__c();
        cms.cel_Campaign__c = c4.Id;
        cms.cel_Contact__c = ctt.Id;
        insert cms;
        
        CampaignMember cm = new CampaignMember();
        cm.CampaignId = c4.Id;
        cm.ContactId = ctt.Id;
        insert cm;
        
        cel_Transaction__c transactions = new cel_Transaction__c();
        transactions.cel_AccountId__c = a.Id;
        transactions.cel_sale_date__c = Date.today();
        insert transactions;
        
        Product2 p1 = new Product2();
        p1.Name = 'Product 01';
        p1.cel_product_category__c = 'BAGS';
        insert p1;
        
        Product2 p2 = new Product2();
        p2.Name = 'Product 02';
        p2.cel_product_category__c = 'SHOES';
        insert p2;
        
        
        cel_Transaction_Line__c line01 = new cel_Transaction_Line__c();
        line01.cel_transaction__c = transactions.Id;
        line01.cel_Product2Id__c = p1.Id;
        line01.cel_net_value_local_tax_inc_eur__c = 100;
        insert line01;
        
        cel_Transaction_Line__c line02 = new cel_Transaction_Line__c();
        line02.cel_transaction__c = transactions.Id;
        line02.cel_Product2Id__c = P2.Id;
        line01.cel_net_value_local_tax_inc_eur__c = 10;
        insert line02;
        
        CEL_KpiCrossSellingBatch batch = new CEL_KpiCrossSellingBatch();
        Database.executeBatch(batch);
        batch.execute(null);
        batch.execute(null, allC);
        Test.stopTest();
    }
}