force-app/main/default/objects/cel_Campaign_Member_Status__c/cel_Campaign_Member_Status__c.object-meta.xml
<CustomObject>
    <label>Campaign Member Status</label>
    <nameField>
        <displayFormat>CMS-{000000}</displayFormat>
        <label>Campaign Member Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Campaign__c.field-meta.xml
<CustomField>
    <fullName>cel_Campaign__c</fullName>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Campaign Member Statuses</relationshipLabel>
    <relationshipName>Campaign_Member_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Confirmed__c.field-meta.xml
<CustomField>
    <fullName>cel_Confirmed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Contact__c.field-meta.xml
<CustomField>
    <fullName>cel_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Clienteling Action History (Contact)</relationshipLabel>
    <relationshipName>Campaign_Member_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Contacted__c.field-meta.xml
<CustomField>
    <fullName>cel_Contacted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contacted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>cel_Customer_Code__c</fullName>
    <formula>cel_Contact__r.Account.cel_ext_account_id__c</formula>
    <label>Customer Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_ext_account_id__c.field-meta.xml
<CustomField>
    <fullName>cel_ext_account_id__c</fullName>
    <description>Customer Code Céline</description>
    <externalId>true</externalId>
    <label>cel_ext_account_id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Invited__c.field-meta.xml
<CustomField>
    <fullName>cel_Invited__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Invited</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_local_Currency__c.field-meta.xml
<CustomField>
    <fullName>cel_local_Currency__c</fullName>
    <label>Local Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
                <default>true</default>
                <label>EUR</label>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>AUD</fullName>
            </value>
            <value>
                <fullName>BHD</fullName>
            </value>
            <value>
                <fullName>CHF</fullName>
            </value>
            <value>
                <fullName>CNY</fullName>
            </value>
            <value>
                <fullName>CZK</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>HKD</fullName>
            </value>
            <value>
                <fullName>IDR</fullName>
            </value>
            <value>
                <fullName>JPY</fullName>
            </value>
            <value>
                <fullName>KRW</fullName>
            </value>
            <value>
                <fullName>KWD</fullName>
            </value>
            <value>
                <fullName>MOP</fullName>
            </value>
            <value>
                <fullName>MYR</fullName>
            </value>
            <value>
                <fullName>QAR</fullName>
            </value>
            <value>
                <fullName>RON</fullName>
            </value>
            <value>
                <fullName>SAR</fullName>
            </value>
            <value>
                <fullName>SEK</fullName>
            </value>
            <value>
                <fullName>SGD</fullName>
            </value>
            <value>
                <fullName>THB</fullName>
            </value>
            <value>
                <fullName>TWD</fullName>
            </value>
            <value>
                <fullName>AED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Member_Name__c.field-meta.xml
<CustomField>
    <fullName>cel_Member_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Member Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clienteling Action History (Customer)</relationshipLabel>
    <relationshipName>Campaign_Member_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Purchasing__c.field-meta.xml
<CustomField>
    <fullName>cel_Purchasing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Purchasing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Res_w_dep__c.field-meta.xml
<CustomField>
    <fullName>cel_Res_w_dep__c</fullName>
    <label>Res w/ dep</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_ResWDep_Euro__c.field-meta.xml
<CustomField>
    <fullName>cel_ResWDep_Euro__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Res w/ dep (€)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_Reswodep__c.field-meta.xml
<CustomField>
    <fullName>cel_Reswodep__c</fullName>
    <label>Res w/o dep</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_ResWODep_Euro__c.field-meta.xml
<CustomField>
    <fullName>cel_ResWODep_Euro__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Res w/o dep (€)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/cel_Campaign_Member_Status__c/fields/cel_show_up__c.field-meta.xml
<CustomField>
    <fullName>cel_show_up__c</fullName>
    <defaultValue>false</defaultValue>
    <label>show-up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CEL_TheContactsController.cls
public class CEL_TheContactsController {
    
    /**
     * getCampaignCurrency : get the current currency of campaign
     * @param  {String} campaignIds
     * @return {Campaign}
     */
    @AuraEnabled
    public static Campaign getCampaignCurrency(String campaignIds){
        Campaign c = new Campaign();
        List<Campaign> listCamp = [SELECT id, ToLabel(cel_local_Currency__c) currencccy FROM campaign WHERE id = : campaignIds];
        
        if(listCamp != null && !listCamp.isEmpty()){
            c = listCamp.get(0);
        }
        
        return c;
    }
    
    /**
     * getCampaignMemberStatusList : Get list of Campaign members status by campaign Id, filterName and customerCode
     * @param  {String} campaignIds
     * @param  {String} filterName description
     * @param  {String} filtCustomerCode
     * @return  {List<cel_Campaign_Member_Status__c>}
     */
    @AuraEnabled
    public static List<cel_Campaign_Member_Status__c> getCampaignMemberStatusList(String campaignIds, String filterName, String filtCustomerCode){
        List<cel_Campaign_Member_Status__c> listCampaMemberStatus = new List<cel_Campaign_Member_Status__c>();
        
        String filterRequest = '';
        String filterCustomerCode = '';
        if(String.isNotBlank(filterName)){
           filterRequest = '%'+filterName+'%';
        }
        if(String.isNotBlank(filtCustomerCode)){
            filterCustomerCode = '%'+filtCustomerCode+'%';
        }
        
        //Add the id of the campaign
        String contactListQuery = 'select cel_Campaign__c, id, cel_Customer_Code__c, cel_Invited__c, cel_Confirmed__c, cel_Contacted__c, ';
            contactListQuery += 'cel_show_up__c,cel_Res_w_dep__c, cel_Reswodep__c, cel_Purchasing__c,cel_ResWDep_Euro__c, ';
            contactListQuery += 'cel_ResWODep_Euro__c, Name, cel_Contact__r.name  ';
            contactListQuery += ' from cel_Campaign_Member_Status__c where cel_Campaign__c = :campaignIds ';
        
        //Filter Name or lastName
        if(String.isNotBlank(filterRequest) && String.isBlank(filterCustomerCode)){
            contactListQuery += '  and (cel_Contact__r.firstName like : filterRequest or cel_Contact__r.lastName like : filterRequest) ';
        }
        
        //customer Code
        if(String.isNotBlank(filterCustomerCode) && String.isBlank(filterRequest)){
            contactListQuery += '  and cel_Customer_Code__c like : filterCustomerCode ';
        }
        
        //Both criteria are mentionned!
        if(String.isNotBlank(filterRequest) && String.isNotBlank(filterCustomerCode)){
            contactListQuery += '  and (cel_Contact__r.firstName like : filterRequest or cel_Contact__r.lastName like : filterRequest OR cel_Customer_Code__c like : filterCustomerCode) ';
        }
        
        //if no filter, then display the members existing
        contactListQuery += ' order by cel_Contact__r.firstName ';
        listCampaMemberStatus = database.query(contactListQuery);
        
        return listCampaMemberStatus;
    }
    
    /**
     * updateTheCampaignMembersStatus : Update the campaign Members Status
     * @param   {List<String>} campaignMembersId
     * @param   {List<Boolean>} inviteds
     * @param   {List<Boolean>} contacteds
     * @param   {List<Boolean>} confirmeds
     * @param   {List<Boolean>} purchasings
     * @param   {List<Decimal>} reswdeps
     * @param   {List<Decimal>} reswodeps
     * @return  {Boolean}
     */
    @AuraEnabled
    public static Boolean updateTheCampaignMembersStatus(List<String> campaignMembersId, List<Boolean> inviteds, List<Boolean> contacteds, List<Boolean> confirmeds, List<Boolean> showups, List<Boolean> purchasings, List<Decimal> reswdeps, List<Decimal> reswodeps){
        Boolean result = false;
        List<cel_Campaign_Member_Status__c> listCms = new List<cel_Campaign_Member_Status__c>();
        integer i = 0;
        for(String cms : campaignMembersId){
            Decimal reswidep = 0;
            Decimal reswoidep = 0;
            reswidep = ( reswdeps != null && reswdeps.get(i)!= null) ? reswdeps.get(i) : 0;
            reswoidep = ( reswodeps != null && reswodeps.get(i)!= null ) ? reswodeps.get(i) : 0;
            
            cel_Campaign_Member_Status__c cmpcst = new cel_Campaign_Member_Status__c(
                id=cms,
                cel_Invited__c =inviteds.get(i),
                cel_Contacted__c = contacteds.get(i),
                cel_Confirmed__c = confirmeds.get(i) ,
                cel_show_up__c = showups.get(i),
                cel_Purchasing__c = purchasings.get(i),
                cel_Res_w_dep__c = reswidep,
                cel_Reswodep__c =  reswoidep );
            
            listCms.add(cmpcst);
            i++;
        }
        
        if(!listCms.isempty()){
            result = true;
            update listCms;
        }
        
        return result;
    }
    
    /**
     * getContacts : get all contacts by campaignId, filterNmae and customerCode
     * @param  {String} campaignIds
     * @param  {String} filterName
     * @param  {String} filtCustomerCode
     * @return {List<Account>}
     */
    @AuraEnabled
    public static List<Account> getContacts(String campaignIds, String filterName, String customerCode){
        Id personAccountRt = CEL_Constants.peronAccountRtID;
        List<account> listAccounts = new List<Account>();
        String filterRequest = '';
        String filterCustomerCode = '';
        
        if(String.isNotBlank(filterName)){
           filterRequest = '%'+filterName+'%';
        }
        
        if(String.isNotBlank(customerCode)){
            filterCustomerCode = '%'+customerCode+'%';
        }
        
        List<cel_Campaign_Member_Status__c> listCampaignMemberStatus = [select id, cel_contact__c
                                                                        from cel_Campaign_Member_Status__c
                                                                        where cel_Campaign__c =: campaignIds];
        Set<String> setContactsToExclude = new Set<String>();
        for(cel_Campaign_Member_Status__c cs : listCampaignMemberStatus){
            setContactsToExclude.add(cs.cel_contact__c);
        }
        
        String contactListQuery = 'SELECT PersonContactID, Name, lastName, firstName, Id, cel_ext_account_id__c, cel_segment_value_label__c, PersonEmail, cel_PersonEmail__c, PersonHomephone ';
        contactListQuery += 'from Account where Recordtypeid = :personAccountRt ';
        
        // name only
        if(String.isNotBlank(filterRequest) && String.isBlank(filterCustomerCode)){
            contactListQuery += ' and Name like : filterRequest ';
        }
        
        //customer Code only
        if(String.isNotBlank(filterCustomerCode) && string.isBlank(filterRequest)){
            contactListQuery += ' and cel_ext_account_id__c like : filterCustomerCode  ';
        }
        
        //Both criteria are mentionned!
        if(String.isNotBlank(filterRequest) && String.isNotBlank(filterCustomerCode)){
            contactListQuery += ' and (Name like : filterRequest OR cel_ext_account_id__c like : filterCustomerCode) ';
        }
        
        //filter on my segments no need !
        if(!setContactsToExclude.isempty()){
            contactListQuery += '  and PersonContactID not in :setContactsToExclude ';
        }
        
        if(filterRequest == '' && filterCustomerCode == ''){
            listAccounts = new List<Account>();
        }
        else{
            contactListQuery += ' order by Name ASC ';
            listAccounts = database.query(contactListQuery);
        }
        
        return listAccounts;
    }
    
    /**
     * addContactToCampaignmemberStatus : Add the campaign Members Status on the campaign current
     * @param  {String} CampaignId
     * @param  {List<String>} listAccountId
     */
    @AuraEnabled
    public static void addContactToCampaignmemberStatus(String CampaignId, List<String> listAccountId){
        List<cel_Campaign_Member_Status__c> lstCampMemberStatus = new List<cel_Campaign_Member_Status__c>();
        List<Account> listAccounts = new List<Account>();
        listAccounts = [select ID, PersonContactID from Account where id in : listAccountId];
        Map<String, String> map_idContact_idAccount = new Map<string, String>();
        
        for(Account c : listAccounts){
            map_idContact_idAccount.put(c.ID, c.PersonContactID);
        }
        
        if(CampaignId != null){
            for(String accountId : listAccountId){
                //afect members to Campaign member Status
                cel_Campaign_Member_Status__c cmpMemStatus = new cel_Campaign_Member_Status__c(
                                                                                                cel_Member_Name__c = accountId,
                                                                                                cel_Campaign__c = CampaignId,
                                                                                                cel_Contact__c = map_idContact_idAccount.get(accountId)
                                                                                            );
                
                lstCampMemberStatus.add(cmpMemStatus);
            }
        } 
        
        if(!lstCampMemberStatus.isEmpty()){
            try{
                insert lstCampMemberStatus;
            }
            catch(Exception ex){
                system.debug('error on creating Campaignmembers CLASS = CEL_TheContactsController '+ lstCampMemberStatus);
            }
        }
    }
    
    /**
     * gotoReportFolderCampaignAction : return link to the report
     * @return {String}
     */
    @AuraEnabled
    public static String gotoReportFolderCampaignAction(){
        return 'lightning/o/Report/home?queryScope=created';
    }
}